package manifest

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Szotasz/connectors-cli/internal/api"
)

// Skill layout (progressive disclosure): SKILL.md carries the frontmatter,
// the operator's local notes and a one-line-per-connector index; every
// connector's full command reference lives in references/<id>.md. A single
// SKILL.md with every tool of every connector grew past 900 lines, which is
// over the Claude Code skill guideline and loads all of it on every use.
const (
	// GeneratedMarker is the first line of every reference file this
	// generator owns. Only files carrying it are ever rewritten or removed.
	GeneratedMarker = "<!-- generated by `connectors sync`: edits here are overwritten -->"

	// Hand-maintained notes between these markers in SKILL.md survive a sync.
	LocalNotesStart = "<!-- local-notes:start (kept by `connectors sync`) -->"
	LocalNotesEnd   = "<!-- local-notes:end -->"

	// A SKILL.md without the markers is saved here before it is replaced,
	// so hand edits made before this layout existed are never lost silently.
	unmarkedBackupName = "SKILL.md.bak-sync"

	// Reference files longer than this get a contents list at the top.
	contentsThreshold = 5
)

func UpdateSkill(m *api.Manifest) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return err
	}
	return updateSkillAt(filepath.Join(home, ".claude", "skills", "connectors-hu"), m)
}

func updateSkillAt(skillDir string, m *api.Manifest) error {
	refDir := filepath.Join(skillDir, "references")
	if err := os.MkdirAll(refDir, 0755); err != nil {
		return err
	}

	skillPath := filepath.Join(skillDir, "SKILL.md")
	notes, err := preserveLocalNotes(skillPath, skillDir)
	if err != nil {
		return err
	}

	toolsByConnector := make(map[string][]api.ToolEntry, len(m.Connectors))
	for _, t := range m.Tools {
		toolsByConnector[t.Connector] = append(toolsByConnector[t.Connector], t)
	}

	keep := make(map[string]bool, len(m.Connectors))
	for _, c := range m.Connectors {
		name := referenceFileName(c.ID)
		keep[name] = true
		path := filepath.Join(refDir, name)
		if err := backupIfNotGenerated(path); err != nil {
			return err
		}
		if err := writeFileAtomic(path, renderReference(c, toolsByConnector[c.ID])); err != nil {
			return err
		}
	}
	if err := removeStaleReferences(refDir, keep); err != nil {
		return err
	}

	return writeFileAtomic(skillPath, renderSkill(m, toolsByConnector, notes))
}

// referenceFileName maps a connector id (e.g. "google_workspace") to its
// reference file ("google-workspace.md").
func referenceFileName(id string) string {
	return strings.ReplaceAll(id, "_", "-") + ".md"
}

func renderSkill(m *api.Manifest, toolsByConnector map[string][]api.ToolEntry, notes string) string {
	// Dynamic description from the manifest's connector list -- keeps the
	// skill description fresh as new connectors land (UNAS, fal.ai, etc.)
	// without requiring a CLI rebuild.
	connectorNames := make([]string, 0, len(m.Connectors))
	for _, c := range m.Connectors {
		connectorNames = append(connectorNames, c.Name)
	}
	connectorList := strings.Join(connectorNames, ", ")
	if connectorList == "" {
		connectorList = "various services"
	}

	var sb strings.Builder
	sb.WriteString("---\n")
	sb.WriteString("name: connectors-hu\n")
	sb.WriteString(fmt.Sprintf("description: CLI for connectors.hu -- business API gateway (%s). Use when user asks to query invoices, partners, tax data, generate AI images, or any connectors.hu operation.\n", connectorList))
	sb.WriteString("---\n\n")
	sb.WriteString("# connectors -- connectors.hu CLI\n\n")
	sb.WriteString("Run `connectors <connector> <command> [flags]` to call connectors.hu APIs.\n\n")

	sb.WriteString(LocalNotesStart + "\n")
	if notes != "" {
		sb.WriteString(notes)
		if !strings.HasSuffix(notes, "\n") {
			sb.WriteString("\n")
		}
	}
	sb.WriteString(LocalNotesEnd + "\n\n")

	sb.WriteString("## Connectors\n\n")
	sb.WriteString("Each connector's full command reference (description + flags) is in its own file. Open the file for the connector you need.\n\n")
	for _, c := range m.Connectors {
		tools := toolsByConnector[c.ID]
		commands := make([]string, 0, len(tools))
		for _, t := range tools {
			commands = append(commands, t.Command)
		}
		sb.WriteString(fmt.Sprintf("- [%s](references/%s) -- `connectors %s` (%d): %s\n",
			c.Name, referenceFileName(c.ID), c.ID, len(tools), strings.Join(commands, ", ")))
	}
	sb.WriteString("\n")

	sb.WriteString("## Usage\n\n")
	sb.WriteString("```bash\n")
	sb.WriteString("export CONNECTORS_HU_TOKEN=cnk_your_api_key\n")
	sb.WriteString("connectors sync              # fetch latest tool manifest\n")
	sb.WriteString("connectors billingo list-documents --per_page 5\n")
	sb.WriteString("connectors nav query-taxpayer --taxNumber 12345678\n")
	sb.WriteString("```\n")
	return sb.String()
}

func renderReference(c api.ConnectorInfo, tools []api.ToolEntry) string {
	var sb strings.Builder
	sb.WriteString(GeneratedMarker + "\n\n")
	sb.WriteString(fmt.Sprintf("# connectors %s -- %s\n\n", c.ID, c.Name))

	if len(tools) > contentsThreshold {
		sb.WriteString("## Contents\n\n")
		for _, t := range tools {
			sb.WriteString(fmt.Sprintf("- connectors %s %s\n", c.ID, t.Command))
		}
		sb.WriteString("\n")
	}

	sb.WriteString(fmt.Sprintf("## %s\n\n", c.Name))
	for _, t := range tools {
		sb.WriteString(fmt.Sprintf("### connectors %s %s\n\n", c.ID, t.Command))
		sb.WriteString(t.Description + "\n\n")

		if len(t.Args) > 0 {
			sb.WriteString("Flags:\n")
			for _, a := range t.Args {
				req := ""
				if a.Required {
					req = " (required)"
				}
				desc := a.Description
				if desc == "" {
					desc = a.Type
				}
				if len(a.Enum) > 0 {
					desc += " [" + strings.Join(a.Enum, "|") + "]"
				}
				sb.WriteString(fmt.Sprintf("  --%s  %s%s\n", a.Name, desc, req))
			}
			sb.WriteString("\n")
		}
	}
	return sb.String()
}

// preserveLocalNotes returns the text between the local-notes markers of the
// existing SKILL.md. A SKILL.md without the markers (written by an older CLI,
// or edited by hand) is copied to SKILL.md.bak-sync first, unless that exact
// content is already saved there.
func preserveLocalNotes(skillPath, skillDir string) (string, error) {
	raw, err := os.ReadFile(skillPath)
	if os.IsNotExist(err) {
		return "", nil
	}
	if err != nil {
		return "", err
	}
	text := string(raw)

	start := strings.Index(text, LocalNotesStart)
	end := strings.Index(text, LocalNotesEnd)
	if start >= 0 && end > start {
		notes := text[start+len(LocalNotesStart) : end]
		return strings.TrimPrefix(notes, "\n"), nil
	}

	if err := saveBackup(skillPath, filepath.Join(skillDir, unmarkedBackupName), text,
		"had no local-notes markers"); err != nil {
		return "", err
	}
	return "", nil
}

// backupIfNotGenerated protects an operator's file that happens to sit at a
// generated reference path (e.g. a hand-split references/billingo.md): it is
// saved as <name>.bak-sync before the generator overwrites it. The same rule
// as removeStaleReferences: a file without the marker is the operator's.
func backupIfNotGenerated(path string) error {
	raw, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	if strings.HasPrefix(string(raw), GeneratedMarker) {
		return nil
	}
	return saveBackup(path, path+".bak-sync", string(raw), "was not written by `connectors sync`")
}

// saveBackup writes text to backup unless that exact content is already
// saved there, and says so on stdout.
func saveBackup(path, backup, text, why string) error {
	if prev, err := os.ReadFile(backup); err == nil && string(prev) == text {
		return nil
	}
	if err := writeFileAtomic(backup, text); err != nil {
		return err
	}
	fmt.Printf("Note: %s %s; the previous version is saved as %s.\n", path, why, backup)
	return nil
}

// removeStaleReferences deletes generated reference files of connectors that
// are no longer in the manifest. Files without the generated marker are the
// operator's and are never touched.
func removeStaleReferences(refDir string, keep map[string]bool) error {
	entries, err := os.ReadDir(refDir)
	if err != nil {
		return err
	}
	for _, e := range entries {
		if e.IsDir() || keep[e.Name()] || !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		path := filepath.Join(refDir, e.Name())
		raw, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if strings.HasPrefix(string(raw), GeneratedMarker) {
			if err := os.Remove(path); err != nil {
				return err
			}
		}
	}
	return nil
}

func writeFileAtomic(path, content string) error {
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}
